import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// =============================================================================
// Better Auth Tables
// =============================================================================

export const user = pgTable(
  "user",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").notNull().default(false),
    image: text("image"),
    isGuest: boolean("is_guest").notNull().default(false),
    username: text("username"), // Unique handle for public profile URL
    bio: text("bio"), // Short profile description
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [uniqueIndex("user_username_idx").on(table.username)],
);

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// =============================================================================
// App & Message Tables (LLM Generation Persistence)
// =============================================================================

/**
 * App represents a vibe coding project/sandbox.
 * Each app has one conversation thread and one sandbox.
 */
export const app = pgTable(
  "app",
  {
    // nanoid, used in URL: /apps/[id]
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // App metadata
    title: text("title"), // Can be AI-generated from initial prompt
    description: text("description"),
    slug: text("slug").unique(), // Optional custom subdomain for sharing
    status: text("status").notNull().default("active"), // 'active' | 'archived'

    // Modal sandbox reference
    sandboxId: text("sandbox_id"), // Modal sandbox object_id (active session)
    snapshotId: text("snapshot_id"), // Modal snapshot image ID (for restore)
    previewUrl: text("preview_url"), // Current Modal tunnel URL

    // Enhanced version of initial prompt (generated by fast LLM)
    enhancedPrompt: text("enhanced_prompt"),

    // Optional GitHub repo linkage for manual push
    githubRepoId: text("github_repo_id"),
    githubRepoOwner: text("github_repo_owner"),
    githubRepoName: text("github_repo_name"),
    githubRepoUrl: text("github_repo_url"),
    githubDefaultBranch: text("github_default_branch"),
    githubLinkedAt: timestamp("github_linked_at"),
    githubLastPushedAt: timestamp("github_last_pushed_at"),

    // Screenshot thumbnail storage key (e.g., "thumbnails/{appId}.png")
    // Presigned URLs are generated on-demand when displaying
    thumbnailKey: text("thumbnail_key"),

    // Social feed / publishing
    isPublished: boolean("is_published").notNull().default(false),
    publishedAt: timestamp("published_at"), // When the app was published to the feed
    likeCount: integer("like_count").notNull().default(0),
    viewCount: integer("view_count").notNull().default(0),
    remixCount: integer("remix_count").notNull().default(0),
    remixedFromId: text("remixed_from_id"), // If this app was remixed from another

    // Aggregated usage stats (for quick dashboard display)
    totalInputTokens: integer("total_input_tokens").notNull().default(0),
    totalOutputTokens: integer("total_output_tokens").notNull().default(0),
    totalCost: numeric("total_cost", { precision: 10, scale: 6 })
      .notNull()
      .default("0"),

    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [
    index("app_user_id_created_at_idx").on(table.userId, table.createdAt),
    index("app_user_id_status_idx").on(table.userId, table.status),
    index("app_slug_idx").on(table.slug),
    index("app_github_repo_id_idx").on(table.githubRepoId),
    index("app_published_at_idx").on(table.isPublished, table.publishedAt),
    index("app_published_likes_idx").on(table.isPublished, table.likeCount),
    index("app_remixed_from_id_idx").on(table.remixedFromId),
  ],
);

/**
 * Message stores individual chat messages with full AI SDK UIMessage compatibility.
 * The `parts` field stores the complete UIMessage.parts array as JSONB.
 */
export const message = pgTable(
  "message",
  {
    // Matches UIMessage.id from AI SDK
    id: text("id").primaryKey(),
    appId: text("app_id")
      .notNull()
      .references(() => app.id, { onDelete: "cascade" }),

    // Message content (UIMessage compatible)
    role: text("role").notNull(), // 'user' | 'assistant' | 'system'
    parts: jsonb("parts").notNull(), // UIMessage.parts array
    metadata: jsonb("metadata"), // UIMessage.metadata (optional)

    // Usage tracking (populated for assistant messages)
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    totalTokens: integer("total_tokens"),
    modelId: text("model_id"), // e.g., 'claude-3-5-sonnet-20241022'
    durationMs: integer("duration_ms"), // Response time
    finishReason: text("finish_reason"), // 'stop' | 'length' | 'tool-calls' | etc

    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    index("message_app_id_created_at_idx").on(table.appId, table.createdAt),
  ],
);

// =============================================================================
// Social Feed Tables
// =============================================================================

/**
 * AppLike tracks which users have liked which apps.
 * Used for the social feed feature.
 */
export const appLike = pgTable(
  "app_like",
  {
    id: text("id").primaryKey(), // nanoid
    appId: text("app_id")
      .notNull()
      .references(() => app.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("app_like_app_user_idx").on(table.appId, table.userId),
    index("app_like_user_id_idx").on(table.userId),
  ],
);

// =============================================================================
// Usage Tracking Tables
// =============================================================================

/**
 * DailyUsage tracks the number of messages a user has sent per day.
 * Used for enforcing global daily message limits across all apps.
 * Date is stored in KL timezone (Asia/Kuala_Lumpur).
 */
export const dailyUsage = pgTable(
  "daily_usage",
  {
    id: text("id").primaryKey(), // nanoid
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    date: text("date").notNull(), // Format: "2026-01-28" (KL timezone)
    messageCount: integer("message_count").notNull().default(0),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [
    unique("daily_usage_user_date_unique").on(table.userId, table.date),
    index("daily_usage_user_id_idx").on(table.userId),
  ],
);

/**
 * GuestDailyUsage tracks anonymous browser quota separately from guest user rows.
 * This prevents guest logout from resetting the browser's daily guest limit.
 */
export const guestDailyUsage = pgTable(
  "guest_daily_usage",
  {
    id: text("id").primaryKey(), // nanoid
    quotaKey: text("quota_key").notNull(),
    date: text("date").notNull(), // Format: "2026-01-28" (KL timezone)
    messageCount: integer("message_count").notNull().default(0),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [
    unique("guest_daily_usage_quota_date_unique").on(
      table.quotaKey,
      table.date,
    ),
    index("guest_daily_usage_quota_key_idx").on(table.quotaKey),
  ],
);

// =============================================================================
// Inspo Table (Curated App Inspiration Gallery)
// =============================================================================

/**
 * Inspo represents a curated example app that users can remix.
 * When remixed, the prompt is used to create a new app.
 */
export const inspo = pgTable(
  "inspo",
  {
    id: text("id").primaryKey(), // nanoid
    title: text("title").notNull(),
    description: text("description").notNull(), // Short display text
    category: text("category").notNull(), // 'games' | 'productivity' | 'utilities' | 'creative'
    prompt: text("prompt").notNull(), // Full prompt used when remixing
    thumbnailUrl: text("thumbnail_url"), // Screenshot URL (external or S3 key)
    featured: boolean("featured").notNull().default(false),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    index("inspo_category_idx").on(table.category),
    index("inspo_featured_idx").on(table.featured),
  ],
);

// =============================================================================
// Type Exports
// =============================================================================

export type User = typeof user.$inferSelect;
export type App = typeof app.$inferSelect;
export type NewApp = typeof app.$inferInsert;
export type Message = typeof message.$inferSelect;
export type NewMessage = typeof message.$inferInsert;
export type AppLike = typeof appLike.$inferSelect;
export type NewAppLike = typeof appLike.$inferInsert;
export type DailyUsage = typeof dailyUsage.$inferSelect;
export type NewDailyUsage = typeof dailyUsage.$inferInsert;
export type Inspo = typeof inspo.$inferSelect;
export type NewInspo = typeof inspo.$inferInsert;
